### ISSUE TITLE
Review work

### ISSUE THREAD

**Issue by Skudoku** [HAN-ASD-DT/trees-assignment-Skudoku#1]
@dvberkel I made an implementation in Swift for the tree assignment. Could you review this work please?

**Comment by dvberkel** [comment]
This looks good. I do have some questions that I love your to hear your answer on. It does not require any changes to the code, if that question would be on your mind.

* [ ] Your implementation mutates a tree, whereas the assignments ask to return a new tree. Could you reflect on the pros and cons of either decision and how that decision might change depending on the language you work in?
* [ ] You addressed Assignment 3, but it is buried in the assignment. Could you explicitly tell how you solved that problem.

**Comment by Skudoku** [comment]
The mutating part is due to me not wanting to keep calling tree = tree.something(), I just wanted to call insert on the tree where it changes, I tried to make it so that it returned a tree but that gave some complications where I am not really sure about anymore what it was, but preference was also a case.

The tree accepts a generic type of which the tree consists, I can init it by doing something like Tree<Int> to say okay this tree will now only accept ints, I could've done Tree<String>, this way I keep track of what kind of objects the tree holds.

**Comment by Skudoku** [comment]
Oh and as far as the unicity of elements, I can see if there are duplicaties by perhaps making a Set (Which is basically a unique set of elements taking into account all of the elements and filters out duplicates) and comparing it's size to the size of the tree itself, I can then check which are duplicates.

**Comment by dvberkel** [comment]
>  I just wanted to call insert on the tree where it changes

This is a personal opinion, do you also have other considerations, thoughts or wisdoms?

**Comment by dvberkel** [comment]
> as far as the unicity of elements

The problem isn't the unicity, rather the opposite. We do want to have multiple similar elements in the tree. How did you achieve that?

**Comment by Skudoku** [comment]
> > I just wanted to call insert on the tree where it changes
> 
> This is a personal opinion, do you also have other considerations, thoughts or wisdoms?

As far as functional programming goes, it isn't mutable, the way I used it is to showcase the power of using functional programming to actually do mutate stuff, which is the case here in particular

**Comment by Skudoku** [comment]
> > as far as the unicity of elements
> 
> The problem isn't the unicity, rather the opposite. We do want to have multiple similar elements in the tree. How did you achieve that?

I'm not really understanding what you mean, you can insert the same element multiple times, it just goes deeper into the tree, in this case, you shouldn't see duplicates if I look at it now, since you add a see kind of tree to the tree, which makes it a part of the tree, so a level deeper, so it is not even equal anymore.

**Comment by dvberkel** [comment]
> > > I just wanted to call insert on the tree where it changes
> > 
> > 
> > This is a personal opinion, do you also have other considerations, thoughts or wisdoms?
> 
> As far as functional programming goes, it isn't mutable, the way I used it is to showcase the power of using functional programming to actually do mutate stuff, which is the case here in particular

Swift allows mutating datastructures which introduces the [aliasing problem](https://en.wikipedia.org/wiki/Aliasing_(computing)). If I would take an other reference into a block, code outside that block could still mutate the tree, without my knowledge.

Elm and some other functional languages don't allow mutation. You can share your datastructures without having to wonder if somebody would mutate it without your knowledge. This opens up the possibility of [persistence](https://en.wikipedia.org/wiki/Persistent_data_structure), allowing data structures to exist after they are operated upon.
